### ISSUE TITLE
first frame preview load only

### ISSUE THREAD

**Issue by tecan** [simonlindholm/toggle-gifs#41] opened 2016-06-22 09:13 UTC
while viewing http://headlikeanorange.tumblr.com/ more than just the first frame seems to get loaded on the GIF files causing the website to take a very long time to load. would be neat to have just the preview image without any of the animation buffered unless hovered over.

**Comment by simonlindholm** [comment] 2016-06-22 11:05
Agreed, but it's more or less impossible with the way the addon is implemented... :(

(Duplicate of #21.)

**Closed by simonlindholm** 2016-06-22 11:05 UTC
