### ISSUE TITLE
Compatibility with Firefox 57

### ISSUE THREAD

**Issue by itwastheband** [simonlindholm/toggle-gifs#44] opened 2017-12-13 22:16 UTC
I looked everywhere to see if I could find whether something was mentioned about this, so apologies if I missed an announcement somewhere - but is there any kind of update in progress to make this extension compatible with Firefox 57?

This extension is a lifesaver and I can't find any other extensions like it that are compatible with the newest version of FF. All the other extensions just freeze the gifs, but I need something that can restart them as well.

If anyone knows of another extension that does the same thing (or if this extension is going to be updated), please let me know!

**Comment by davidism** [comment] 2017-12-15 16:31
duplicate of #43

**Comment by itwastheband** [comment] 2017-12-15 19:22
Thank you! The title threw me off and made me think it was regarding
another issue, but it makes sense now.

**Closed as completed** 2017-12-15 19:23 UTC
